# Generated by Django 5.2.6 on 2025-09-18 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regiao',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('sigla', models.CharField(max_length=2, unique=True, verbose_name='Sigla da Região')),
            ],
        ),
        migrations.CreateModel(
            name='UF',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('sigla', models.CharField(max_length=2, unique=True, verbose_name='Sigla da Unidade da Federação')),
                ('regiao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cidades.regiao')),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('uf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cidades.uf')),
            ],
        ),
    ]
