# Generated by Django 5.2.6 on 2025-09-18 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regiao',
            name='sigla',
            field=models.CharField(max_length=2, verbose_name='Sigla da Região'),
        ),
        migrations.AlterField(
            model_name='uf',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
